# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "848252c433f59166752563c1785b2c41"
name = "raffle-app"
handle = "raffle-app-11"
application_url = "https://shops-partner-equation-implementing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://shops-partner-equation-implementing.trycloudflare.com/auth/callback", "https://shops-partner-equation-implementing.trycloudflare.com/auth/shopify/callback", "https://shops-partner-equation-implementing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
