# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "848252c433f59166752563c1785b2c41"
name = "raffle-app"
handle = "raffle-app-11"
application_url = "https://charger-tasks-hudson-prepare.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,write_metaobjects,write_products"

[auth]
redirect_urls = ["https://charger-tasks-hudson-prepare.trycloudflare.com/auth/callback", "https://charger-tasks-hudson-prepare.trycloudflare.com/auth/shopify/callback", "https://charger-tasks-hudson-prepare.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
